### ISSUE TITLE
Parse error on UA string

### ISSUE THREAD

**Issue by ghost** [woothee/lua-resty-woothee#1]
On a large-load system I am seeing the following error repeatedly.

This is on an Open-Resty platform, release 1.7.10.2.

The following is what we are seeing.
Is this an issue with the Woothee data being used?

We are seeing this intermittently.

> 2015/07/22 12:53:25 [error] 9783#0: *2702384 lua entry thread aborted: runtime error: ...ocal/openresty/luajit/share/lua/5.1/resty/woothee/os.lua:55: attempt to index local 'match' (a nil value)
> stack traceback:
> coroutine 0:
>   ...ocal/openresty/luajit/share/lua/5.1/resty/woothee/os.lua: in function 'challenge_windows'
>   /usr/local/openresty/luajit/share/lua/5.1/resty/woothee.lua:45: in function 'try_os'
>   /usr/local/openresty/luajit/share/lua/5.1/resty/woothee.lua:165: in function 'exec_parse'
>   /usr/local/openresty/luajit/share/lua/5.1/resty/woothee.lua:222: in function 'parse'

**Comment by toritori0318** [comment]
@rcritt 
Thank you for your feedback!

fixed.
https://github.com/woothee/lua-resty-woothee/commit/01b926a1268085b97e6301d5b9b318b211c4d717

I would like to add testset, Can you please give me information on UserAgent?

**Comment by ghost** [comment]
I think the error is reproducible with this string we are seeing in the user-agents.

> local parseResult = woothee.parse("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240")

Thank you again for your help on this!

**Comment by toritori0318** [comment]
Thank you for your cooperation!
