### ISSUE TITLE
another global variable

### ISSUE THREAD

**Issue by stanojr** [woothee/lua-resty-woothee#10]
hi, i catch another global variable

2019/06/21 19:45:45 [warn] 21777#0: *93664160 [lua] _G write guard:12: __newindex(): writing a global lua variable ('version') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
	/usr/local/share/lua/5.1/resty/woothee/browser.lua:47: in function 'challenge_safari_chrome'
	/usr/local/share/lua/5.1/resty/woothee.lua:37: in function 'try_browser'
	/usr/local/share/lua/5.1/resty/woothee.lua:176: in function 'exec_parse'
	/usr/local/share/lua/5.1/resty/woothee.lua:234: in function 'parse'
	/opt/ngx-openresty/nginx/conf/proxy/log.lua:3: in main chunk while logging request, client: 1.2.3.4, server: , request: "GET / HTTP/1.1", upstream: "http://10.1.1.1/", host: "xxx"

**Comment by toritori0318** [comment]
@stanojr I am sorry for taking up so much of your time..
I fix it, and update Openresty container to latest version for testing.

**Comment by toritori0318** [comment]
All global variables checked by luacheck.
