### ISSUE TITLE
Wrong browser detected for user agent

### ISSUE THREAD

**Issue by bogdanpetrea** [woothee/lua-resty-woothee#4]
Hi,
For `Android: Mozilla/5.0 (Linux; Android 7.0; SM-G950U Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.107 Mobile Safari/537.36 Snapchat/10.17.0.0 (SM-G950U; Android 7.0#G950USQU1AQG4#24; gzip)`, the browser is being detected as `Webview` instead of `Chrome`.
Using the demo from http://woothee.github.io/ says the browser is `Chrome`.

**Comment by toritori0318** [comment]
Hi, @bogdanpetrea !
Thank you for your report.

`Webview` is the correct answer. 
[Demo site](http://woothee.github.io/ ) is running with old version. So it is a wrong result.

**Comment by bogdanpetrea** [comment]
Hey @toritori0318,
Thanks for the input!
I'm not very familiar with UA parsing, but I assume Webview is correct because of the `wv` and `Snapchat` parts in the UA.

https://developers.whatismybrowser.com/useragents/parse/#parse-useragent
https://www.whatsmyua.info/
https://helloacm.com/parse-user-agent/
all say it's Chrome though. Guess they could all be wrong.
