### ISSUE TITLE
global lua variable

### ISSUE THREAD

**Issue by stanojr** [woothee/lua-resty-woothee#8]
In latest openresty 1.15.8.1 there is error 
2019/06/15 13:08:51 [warn] 25052#0: *23886 [lua] _G write guard:12: __newindex(): writing a global lua variable ('taget') which may lead to race conditions between concurren
t requests, so prefer the use of 'local' variables
stack traceback:
        /usr/local/share/lua/5.1/resty/woothee/util.lua:6: in function 'update_map'
        /usr/local/share/lua/5.1/resty/woothee/browser.lua:101: in function 'challenge_firefox'
        /usr/local/share/lua/5.1/resty/woothee.lua:41: in function 'try_browser'
        /usr/local/share/lua/5.1/resty/woothee.lua:176: in function 'exec_parse'
        /usr/local/share/lua/5.1/resty/woothee.lua:234: in function 'parse'

I think there is typo in util.lua "taget" instead of "target"

**Comment by toritori0318** [comment]
@stanojr Thank you for reporting!
oops :(   It seems that it was wrong.
I will fix it soon.

**Comment by toritori0318** [comment]
Fixed it. https://github.com/woothee/lua-resty-woothee/pull/9
Thanks!
